database:
  ConnectionStrings:
    default: "Host=127.0.0.1;Database=openmod;Port=3306;Username=root;Password=toor;" 
steamWebApiKey: "" # Get your WebApiKey from https://steamcommunity.com/dev/apikey. Not setting one up simply will result in profile picture URLs not updating or being retrieved at all.